### ISSUE TITLE
Deprecation on UrlGenerator::generate method

### ISSUE THREAD

**Issue by JHGitty** [KnpLabs/KnpMenuBundle#291]
```
The hardcoded value you are using for the $referenceType argument of the Symfony\Component\Routing\Generator\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead. 

Called from UrlGenerator::doGenerate() at line 141
Called from appDevUrlGenerator::generate() at line 1284
Called from Router::generate() at line 26
Called from RoutingExtension::buildOptions() at line 31
Called from MenuFactory::createItem() at line 342
Called from MenuItem::addChild() at line 22
Called from Builder::testMenu() at line 60
```

**Comment by JulienDemangeon** [comment]
:+1:  A tag on this PR would be really helpful

**Comment by stof** [comment]
this is planned for the weekend

**Comment by JulienDemangeon** [comment]
Thanks :)

**Comment by JulienDemangeon** [comment]
The new tag doesn't include this fix. =/

**Comment by dbu** [comment]
not sure there was any new tag on KnpMenu. i only tagged KnpMenuBundle yesterday.

**Comment by JulienDemangeon** [comment]
Sorry for the mistake, this is ready to be tagged on KnpMenu.  https://github.com/KnpLabs/KnpMenu/pull/226

**Comment by dbu** [comment]
@Stof any reason not to tag a patch release of KnpMenu?

**Comment by stof** [comment]
@dbu I was busy during the evenings, and so haven't done OSS stuff

**Comment by dbu** [comment]
stof, that was not meant as reproach but as question whether i can tag it or whether i should wait for something. i will update the CHANGELOG this time, too ;-)

**Comment by JulienDemangeon** [comment]
There's something new about this ?

**Comment by JHGitty** [comment]
@stof Merry Christmas! :smile: Could you (or is @dbu allowed to) work on this?

**Comment by dbu** [comment]
i would do it but am waiting for confirmation by stof whether its ok to do it at this point.

**Comment by JulienDemangeon** [comment]
:+1:

**Comment by yannickl88** [comment]
:+1: Some more news about this issue? We are eager to update to a version where this issue is fixed.

**Comment by dbu** [comment]
tagged https://github.com/KnpLabs/KnpMenu/releases/tag/v2.1.1

**Comment by atierant** [comment]
Bump ! I have to keep my 2.8 for now... Thanks

**Comment by stof** [comment]
@atierant why are you bumping this ? A tag has been created, as linked in comment before yours

**Comment by atierant** [comment]
@stof Hi ! Because I'm in 2.1.1 and I still have the deprecation warning.

**Comment by JHGitty** [comment]
@atierant Please cleanup your cache. Which deprecation warning do you get? Please write it here in a code block or open a new issue about it if it is different than this one.

**Comment by atierant** [comment]
@JHGitty @stof My mistake ! It was my Symfony CMF, as seen here http://stackoverflow.com/questions/35689012/urlgeneratorgenerate-triggers-deprecation-notice
Not KNP Menu fault... Sorry for bumping :)
